weather:
  monitoring:
    -
      cityId: 2643743
      cityName: "London"
      frequency: 2000
      threshold: 10
    -
      cityId: 2643743
      cityName: "Tel Aviv"
      frequency: 4000
      threshold: 15
    -
      cityId: 2643743
      cityName: "New York"
      frequency: 3000
      threshold: 20





